spring.application.name=oficina

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=miguel04

oficina.negocio.salario.atendente=1000.00
oficina.negocio.salario.mecanico=1500.00
oficina.negocio.custo.mao-de-obra=150.00
oficina.negocio.comissao.percentual=0.05
oficina.negocio.taxa-cancelamento.valor=30.00
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info

