spring.application.name=oficina
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

oficina.negocio.salario.atendente=${OFICINA_NEGOCIO_SALARIO_ATENDENTE}
oficina.negocio.salario.mecanico=${OFICINA_NEGOCIO_SALARIO_MECANICO}
oficina.negocio.custo.mao-de-obra=${OFICINA_NEGOCIO_CUSTO_MAO_DE_OBRA}
oficina.negocio.comissao.percentual=${OFICINA_NEGOCIO_COMISSAO_PERCENTUAL}
oficina.negocio.taxa-cancelamento.valor=${OFICINA_NEGOCIO_TAXA_CANCELAMENTO_VALOR}
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info

