spring.application.name=oficina

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username= postgres
spring.datasource.password=miguel04
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true



oficina.negocio.salario.atendente=1000.00
oficina.negocio.salario.mecanico=1500.00
oficina.negocio.custo.mao-de-obra=150.00
oficina.negocio.comissao.percentual=0.05 # Comissão de 5%
oficina.negocio.taxa-cancelamento.valor=30.00

