package miguel.projetos.oficina.Controller;

import miguel.projetos.oficina.dto.ClienteCreateDto;
import miguel.projetos.oficina.dto.ClienteDto;
import miguel.projetos.oficina.entity.Cliente;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import miguel.projetos.oficina.service.ClienteService;

import java.util.List;
import java.util.NoSuchElementException; // Example for an exception thrown by service

@RestController
@RequestMapping("/api/clientes")
public class ClienteController {

    @Autowired
    ClienteService clienteService;

    @GetMapping
    public ResponseEntity<List<ClienteDto>> getAll() {
        // Using .stream().map().toList() is fine for Java 16+
        List<ClienteDto> clientes = clienteService.findAll().stream()
                .map(this::convertToDto)
                .toList(); // If using Java 11-15, use .collect(Collectors.toList())
        return ResponseEntity.ok(clientes);
    }

    @GetMapping("/cpf/{cpf}")
    public ResponseEntity<ClienteDto> getClienteByCpf(@PathVariable String cpf) {
        return clienteService.findByCpf(cpf)
                .map(this::convertToDto) // Use method reference for clarity
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<ClienteDto> create(@Valid @RequestBody ClienteCreateDto clienteCreateDto) {
        // Corrected variable name
        Cliente clienteParaSalvar = convertCreateDtoToEntity(clienteCreateDto);
        Cliente clienteSalvo = clienteService.save(clienteParaSalvar);
        return ResponseEntity.status(HttpStatus.CREATED).body(convertToDto(clienteSalvo));
    }

    @PutMapping("/cpf/{cpf}")
    public ResponseEntity<ClienteDto> updateCliente(@PathVariable String cpf, @Valid @RequestBody ClienteDto updateDto) {
        try {
            Cliente clienteAtualizado = clienteService.update(cpf, updateDto);
            return ResponseEntity.ok(convertToDto(clienteAtualizado));
        } catch (NoSuchElementException e) { // Assuming service throws this if not found
            return ResponseEntity.notFound().build();
        } catch (IllegalArgumentException e) { // Example for invalid input
            return ResponseEntity.badRequest().build();
        }
    }

    @DeleteMapping("/cpf/{cpf}")
    public ResponseEntity<Void> deleteCliente(@PathVariable String cpf) { // Return Void for no content
        try {
            clienteService.delete(cpf);
            return ResponseEntity.noContent().build();
        } catch (IllegalArgumentException e) { // Client not found
            return ResponseEntity.notFound().build();
        } catch (IllegalStateException e) { // Conflict (e.g., client has associated orders)
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }

    // --- Helper Methods ---
    private ClienteDto convertToDto(Cliente cliente) {
        ClienteDto dto = new ClienteDto();
        dto.setCpf(cliente.getCpf());
        dto.setNome(cliente.getNome());
        dto.setTelefone(cliente.getTelefone());
        dto.setEndereco(cliente.getEndereco());
        dto.setEmail(cliente.getEmail());
        return dto;
    }

    // Renamed for consistency with the call in 'create' method
    private Cliente convertCreateDtoToEntity(ClienteCreateDto createDto) {
        Cliente cliente = new Cliente();
        // The ID is not defined here, as it will be generated by the service
        cliente.setCpf(createDto.getCpf());
        cliente.setNome(createDto.getNome());
        cliente.setTelefone(createDto.getTelefone());
        cliente.setEndereco(createDto.getEndereco());
        cliente.setEmail(createDto.getEmail());
        return cliente;
    }
}